server:
  port: 8989
#  port: ${PORT:8989}

#server:
#  port: 9411
  
info:
  component: Turbine

#PREFIX:
  
#endpoints:
#  restart:
#    enabled: true
#  shutdown:
#    enabled: true

#management:
#  port: 8990

logging:
  level:
    root: INFO
    com.netflix.discovery: 'OFF'
    # org.springframework.integration: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://discUser:discPassword@localhost:8761/eureka/      

turbine:
  appConfig: UI
  clusterNameExpression: "'default'"
#  aggregator:
#    clusterConfig: UI
#  appConfig: ui
#  clusterNameExpression: metadata['cluster']
#  
#
  
  
spring:
  rabbitmq:
    username: user
    password: bitnami 
#    port: 5672
  
#---
#spring:
#  profiles: cloud
#management:
#  port: -1      

---
spring:
  profiles: docker
  redis:
    host: redis
    port: 6379   
  zipkin:
    baseUrl: http://tracing:9411/
    
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl: 
      defaultZone: http://discUser:discPassword@discovery:8761/eureka/      
        