server:
  port: 9411

logging:
  level: 
    org.springframework.web: debug

---
spring:
  profiles: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    serviceUrl:
      defaultZone: http://discUser:discPassword@localhost:8761/eureka/      

---
spring:
  profiles: docker
  redis:
    host: redis
    port: 6379     
  
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl: 
      defaultZone: http://discUser:discPassword@discovery:8761/eureka/      
        