server:
  port: 9000

security:
  sessions: NEVER

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl: 
      defaultZone: http://discUser:discPassword@discovery:8761/eureka/      
      
    
spring:
  profiles: docker
  session:
    store-type: redis  
  redis:
    host: redis
    port: 6379   
  rabbitmq:
    host: rabbit
    port: 5672
    username: test
    password: test    
  zipkin:
    baseUrl: http://tracing:9411/        
    
logging:
  level: 
    org.springframework.security: DEBUG
    