server:
  port: 9000

security:
  sessions: NEVER

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discUser:discPassword@localhost:8761/eureka/
  instance:
    hostname: localhost
    
spring:
  profiles: default
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379       
  rabbitmq:
    username: user
    password: bitnami        
    
logging:
  level: 
    org.springframework.security: DEBUG
    
