server:
  port: 8082
spring:
  session:
    store-type: redis
logging:
  level:
    org.springframework.security: DEBUG
#security:
#  user:
#    role: USER,ADMIN
  ignored:
  - "*.bundle.*"
#  sessions: NEVER

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5  
    serviceUrl:
      defaultZone: http://discUser:discPassword@localhost:8761/eureka/   


---
spring:
  profiles: docker
  redis:
    host: redis
    port: 6379   
  rabbitmq:
    host: rabbit
    port: 5672
    username: user
    password: bitnami
  zipkin:
    baseUrl: http://tracing:9411/    

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl: 
      defaultZone: http://discUser:discPassword@discovery:8761/eureka/      
        