server:
  port: 8082
spring:
  session:
    store-type: redis
logging:
  level:
    org.springframework.security: DEBUG
#security:
#  user:
#    role: USER,ADMIN
  ignored:
  - "*.bundle.*"
#  sessions: NEVER

eureka:
  client:
    serviceUrl:
      defaultZone: http://discUser:discPassword@localhost:8761/eureka/   
