logging:
  level:
    org.springframework.security: DEBUG
security:
  sessions: ALWAYS
  ignored:
  - "*.bundle.*"
  - favicon.ico
spring:
  session:
    store-type: redis
zuul:
  routes:
    ui:
#      url: http://localhost:8081
      path: /ui/**
      sensitive-headers:
      serviceId: ui
    adminui:
#      url: http://localhost:8082
      path: /adminui/**
      sensitive-headers:
      serviceId: adminui
    resource:
#      url: http://localhost:9000
      path: /resource/**
      sensitive-headers:
      serviceId: resource
      
    
