eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl: 
      defaultZone: http://discUser:discPassword@localhost:8761/eureka/
#    
#security:
#  sessions: ALWAYS
#  ignored:
#  - "*.bundle.*"
#  - favicon.ico
spring:
  session:
    store-type: redis
  cloud: 
    config:
      username: configUser
      password: configPassword
      
        
server:
  port: 8761
  
---
spring:
  profiles: docker
  redis:
    host: redis
    port: 6379   
#  zipkin:
#    baseUrl: http://tracing:9411/
    
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl: 
      defaultZone: http://discUser:discPassword@discovery:8761/eureka/
